on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.0"
          - "2.7"
          - "2.6"
        gemfile:
          - "Gemfile.dry-config.0.12"
          - "Gemfile.dry-config.0.14"
        exclude:
          - ruby: "2.6"
            gemfile: "Gemfile.dry-config.0.14"
    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run unit tests
        run: bundle exec rspec
